language: perl

perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

services:
  - memcached

before_install:
  # Install Berkeley DB for installing DB_File module.
  # libperl-dev for installing ImageMagick.
  # php5, php5-mysql, php5-gd for tests of dynamic publishing.
  # libpng12-dev, libgif-dev and libjpeg-dev for Imager.
  - sudo apt-get update
  - sudo apt-get install libdb-dev libgd2-xpm-dev libgmp3-dev libperl-dev php5 php5-mysql php5-gd libpng12-dev libgif-dev libjpeg-dev

  # PHPUnit
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit

install:
  # Install ImageMagick for installing Image::Magick.
  - mkdir local
  - cd local
  - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xzvf ImageMagick.tar.gz
  - cd ImageMagick-*
  - ./configure --prefix=${HOME}/local --with-perl=${HOME}/perl5/perlbrew/perls/${TRAVIS_PERL_VERSION}/bin/perl
  - make
  - sudo make install
  - cd ../../

  # Instal CPAN modules.
  - cpanm -n Crypt::CBC
  - travis_retry cpanm -n --installdeps . --cpanfile ./t/cpanfile

  # Build MT.
  #- SHELL=/bin/bash make me

before_script:
  # Create MySQL database for tests.
  - mysql -e "create database mt_test;"
  - mysql -uroot -e "grant all privileges on mt_test.* to mt@localhost;"

  # Some tests need mt-config.cgi.
  - cp ./t/mysql-test.cfg ./mt-config.cgi

  # Remove failed tests.
  - rm t/34-sqlite.t
  - rm t/90-podcoverage.t

script:
  - bash -c "PERL_HASH_SEED=0 MT_TEST_PARALLEL=1 prove -j2 t plugins/*/t && phpunit"

